### ISSUE TITLE
Version 2.0 roadmap

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#1652]
### Replace all global singletons with services
- [x] Convert CM_Memcache_Client into a service #1654
- [x] Convert CM_Elasticsearch_Client into a service #1653
- [ ] Convert Caches into services #1655
- [x] Convert CM_Adprovider into a service #1658
- [ ] Convert Gearman into JobManager service #1659
- [x] Convert CM_Option into a service #1661
- [x] Convert CMService_Newrelic into a service #1663
- [x] Convert CM_Debug into a service #1664
- [x] Convert CM_Stream_Video into a service #1665
- [x] Convert CM_Stream_Message into a service #1666
- [ ] Convert CM_Render into a service
- [ ] Convert Mail Delivery into a service
- [ ] Introduce "CodeRepository" service
- [ ] Introduce "ModelRepository" service
- [x] Introduce CM_Util_NamedArgs for easier services configuration #1662
### Update scripts
- [ ] convert update script to classes - use ProvisionScript class (_consider naming udpates scripts, consider suffixing numbered update scripts_) - see https://github.com/cargomedia/CM/issues/588 and #1870
### Remove global state

Replace singleton accessors with dependency injection.
- [ ] Remove global constants
- [ ] Remove global service manager
  - [ ] Store service manager on cli manager, pass manager to commands / runnables
  - [ ] Remove CM_ServiceManager singleton usages _(test cases, CM_File, Update scripts, etc)_
- [ ] Move boostraping from CM_Bootloader to CM_Application
  _Consider making CM_Application an abstract class (make CommandManager and HttpHandler its children)._
### Helpers
- introduce `CM_Schema_Definition`, `CM_Schema_Field`
- make `CM_Model_Schema_Definition` extend `CM_Schema_Definition`
- add `CM_Model_Schema_Definition::getSchema()`
- add `CM_Form_Abstract->registerFieldsFromSchemaDefinition(CM_Schema_Definition $schema)`
### New project creation notes
- upgrade web entry point
- nginx configuration doesn't support `modules/**/*.js` files loading
- add creation of the layout
- separate creation of the web application and cli application?
- create tables, collections from schemas instead of sql/json files
- improve creation of schema 
  - atm you need to know all the types to create proper schema - more oop?
  - introduce `Schema_Field`?
- add `CM_PagingSource_Model`
- convert CM_FormAction to CM_Form `action*` method
# 

This is a proposal of major framework version release. 
At the moment CM framework is one big monolith, all the parts of the framework relies on each other and it's quite impossible to extract any module as separate, alone-working part. Also our tests are using global state which means to test something we need to change it (global state) and revert it after test is done. This also prevents us from using multi-threaded tests as most of them conflicts when used at the same time.

As said it's loose draft which could be changed or extended once new problems arise. I would be really glad if everyone who's into it could participate.

**Comment by tomaszdurka** [comment]
Hi @njam, wanted to first ask you wdyt about this kind of issue? I wanted to invite all our CM-connected devs to participate, but I would prefer to not absorb them too much too :panda_face:

**Comment by njam** [comment]
It looks good afaict. I'd suggest to *not* place them in `CM/Service/`, but rather in a separator *topic module* - wdyt?

**Comment by tomaszdurka** [comment]
@alexispeter @fauvel @dlondero @mariansollmann 
Would be great if you guys participate, comment on various issues, etc. Thanks.

**Comment by tomaszdurka** [comment]
@njam Yes, I agree.
